version: '2'
networks:
  app-tier:
    driver: bridge
services:

  vbaby_mobile:
    dns: 8.8.8.8
    networks:
      - app-tier
    image: vbaby/mobile
    container_name: mobile
    build: ./vbaby_mobile
    volumes:
      - ./vbaby_mobile:/var/www/html/app
    ports:
      - "8000:80"
    entrypoint: /var/www/html/app/entrypoint.sh
    working_dir: /var/www/html/app

  vbaby_api:
    dns: 8.8.8.8
    networks:
      - app-tier
    image: vbaby/phpapi
    container_name: phpapi
    build: ./vbaby_api
    ports:
      - "8001:80"
    volumes:
      - ./vbaby_api:/var/www/html/app
    entrypoint: /var/www/html/app/entrypoint.sh
    working_dir: /var/www/html/app

  mysql:
    dns: 8.8.8.8
    networks:
      - app-tier
    container_name: mysql
    image: vietcode/mysql
    volumes:
      - ./vbaby_mysql/data:/var/lib/mysql
      - ./vbaby_mysql/run:/var/run/mysqld
    ports:
      - '3306:3306'
#
