version: '2'
networks:
  app-tier:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/24
        gateway: 172.19.0.1

services:
  webapp:
    image: ubuntu
    dns: 8.8.8.8
    env_file: .env
  vbaby_mobile:
    extends:
      service: webapp
    networks:
      app-tier:
        ipv4_address: ${MOBILE_IPADDRESS}
    image: vietcode/nodejs7
    container_name: vbaby_mobile
    build: ./vbaby_mobile
    volumes:
      - ./vbaby_mobile:/var/www/html/app
    ports:
      - "8000:80"
    entrypoint: /var/www/html/app/entrypoint.sh
    working_dir: /var/www/html/app
    environment:
      PHPAPI_IPADDRESS: ${PHPAPI_IPADDRESS}

  vbaby_api:
    networks:
      app-tier:
        ipv4_address: ${PHPAPI_IPADDRESS}
    image: vbaby/phpapi
    container_name: vbaby_api
    build: ./vbaby_api
    ports:
      - "8001:80"
    volumes:
      - ./vbaby_api:/var/www/html/app
    entrypoint: /var/www/html/app/entrypoint.sh
    working_dir: /var/www/html/app
    environment:
      MYSQL_IPADDRESS: ${DB_IPADDRESS}

  vbaby_db:
    networks:
      app-tier:
        ipv4_address: ${DB_IPADDRESS}
    container_name: vbaby_db
    image: vietcode/mariadb
    ports:
      - '3306:3306'
    environment:
      DB_NAME: "vbaby"
    entrypoint: /data/entrypoint.sh
    volumes:
        - ./vbaby_db:/data

#
