version: '2'
networks:
  app-tier:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/24
        gateway: 172.19.0.1

services:


  vbaby_api:
    env_file:
      - .env
      - ./vbaby_api/.env
    dns: 8.8.8.8
    networks:
      app-tier:
        ipv4_address: ${API_IPADDRESS}
    image: vbaby/api
    container_name: vbaby_api
    build: ./vbaby_api
    ports:
      - "8001:80"
    volumes:
      - ./vbaby_api:${APP_SOURCE_PATH}
    working_dir: ${APP_SOURCE_PATH}
    environment:
      DOCUMENT_ROOT: ${API_DOCUMENT_ROOT}


  vbaby_mobile:
    env_file:
      - .env
      - ./vbaby_mobile/.env
    dns: 8.8.8.8
    networks:
      app-tier:
        ipv4_address: ${MOBILE_IPADDRESS}
    image: vbaby/mobile
    container_name: vbaby_mobile
    build: ./vbaby_mobile
    volumes:
      - ./vbaby_mobile:${APP_SOURCE_PATH}
    ports:
      - "8000:80"
    working_dir: ${APP_SOURCE_PATH}
    command:
      - npm install
      - ionic serve


  vbaby_db:
    env_file:
      - vbaby_api/.env
      - .env
    networks:
      app-tier:
        ipv4_address: ${DB_IPADDRESS}
    container_name: vbaby_db
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${API_DB_DATABASE}
      MYSQL_USER: ${API_DB_USERNAME}
      MYSQL_PASSWORD: ${API_DB_PASSWORD}

#
